name: MoonlightingSessions.com
favicon: null
layout_spectrum: 0.8905
typography_spectrum: 0.26598441740497947
title: moonlightings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#662c91'
    - '#231f20'
    - '#8d62ad'
    - '#af92c6'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
